const dutch = [
  {
    words: [
      { word: "ongeveer", meaning: "approximately" },
      { word: "echt", meaning: "real" },
      { word: "vooral", meaning: "especially" },
      { word: "natuurlijk", meaning: "naturally" },
      { word: "even", meaning: "even" },
      { word: "zelfs", meaning: "even" },
      { word: "toch", meaning: "yet" },
      { word: "binnenkort", meaning: "soon" },
      { word: "opnieuw", meaning: "again" },
      { word: "gewoon", meaning: "just" },
    ],
    name: "Adverbs 2",
  },
  {
    words: [
      { word: "schrijver", meaning: "writer (male)" },
      { word: "baan", meaning: "job" },
      { word: "schrijfster", meaning: "writer (female)" },
      { word: "student", meaning: "student (male)" },
      { word: "studente", meaning: "student (female)" },
      { word: "werk", meaning: "work" },
      { word: "carrière", meaning: "career" },
      { word: "model", meaning: "model" },
      { word: "kunstenaar", meaning: "artist (male)" },
      { word: "kunstenares", meaning: "artist (female)" },
    ],
    name: "Occupations",
  },
  {
    words: [
      { word: "zingen", meaning: "to sing" },
      { word: "gaan", meaning: "to go" },
      { word: "zwemmen", meaning: "to swim" },
      { word: "winnen", meaning: "to win" },
      { word: "verliezen", meaning: "to lose" },
      { word: "fietsen", meaning: "to cycle" },
      { word: "rennen", meaning: "to run" },
      { word: "presenteren", meaning: "to present" },
      { word: "leven", meaning: "to live" },
      { word: "denken", meaning: "to think" },
    ],
    name: "The gerund",
  },
  {
    words: [
      { word: "vriezer", meaning: "freezer" },
      { word: "koelkast", meaning: "refrigerator" },
      { word: "magnetron", meaning: "microwave" },
      { word: "fornuis", meaning: "stove" },
      { word: "oven", meaning: "oven" },
      { word: "hap", meaning: "bite" },
      { word: "roeren", meaning: "to stir" },
      { word: "snijden", meaning: "to cut" },
      { word: "lusten", meaning: "to like (food)" },
      { word: "bakken", meaning: "to bake" },
    ],
    name: "Kitchen",
  },
  {
    words: [
      { word: "volgens", meaning: "according to" },
      { word: "sinds", meaning: "since" },
      { word: "dankzij", meaning: "thanks to" },
      { word: "behalve", meaning: "except for" },
      { word: "ondanks", meaning: "despite" },
      { word: "tegenover", meaning: "opposite" },
      { word: "voorbij", meaning: "past" },
      { word: "vanaf", meaning: "from (a point in time)" },
      { word: "langs", meaning: "along" },
      { word: "rondom", meaning: "around" },
    ],
    name: "Prepositions 2",
  },
  {
    words: [
      { word: "succes", meaning: "success" },
      { word: "verschil", meaning: "difference" },
      { word: "leven", meaning: "life" },
      { word: "dood", meaning: "death" },
      { word: "fout", meaning: "mistake" },
      { word: "kans", meaning: "chance" },
      { word: "situatie", meaning: "situation" },
      { word: "gebeurtenis", meaning: "event" },
      { word: "nadeel", meaning: "disadvantage" },
      { word: "geheim", meaning: "secret" },
    ],
    name: "Asbtract Objects 1",
  },
  {
    words: [
      { word: "verhaal", meaning: "story" },
      { word: "vertellen", meaning: "to tell" },
      { word: "sturen", meaning: "to send" },
      { word: "brief", meaning: "letter" },
      { word: "informatie", meaning: "information" },
      { word: "post", meaning: "mail" },
      { word: "discussie", meaning: "discussion" },
      { word: "gesprek", meaning: "conversation" },
      { word: "communicatie", meaning: "communication" },
      { word: "bericht", meaning: "message" },
    ],
    name: "Communication",
  },
  {
    words: [
      { word: "prehistorie", meaning: "prehistory" },
      { word: "ridder", meaning: "knight" },
      { word: "middeleeuwen", meaning: "Middle Ages" },
      { word: "rijk", meaning: "empire" },
      { word: "aanval", meaning: "attack" },
      { word: "archeoloog", meaning: "archaeologist" },
      { word: "burgeroorlog", meaning: "civil war" },
      { word: "onafhankelijkheid", meaning: "independence" },
      { word: "tachtigjarige", meaning: "Eighty Years' War" },
      { word: "veldslag", meaning: "battle" },
    ],
    name: "Events",
  },
  {
    words: [
      { word: "leraar", meaning: "teacher (male)" },
      { word: "onderwijs", meaning: "education" },
      { word: "school", meaning: "school" },
      { word: "les", meaning: "lesson" },
      { word: "klas", meaning: "class" },
      { word: "leerling", meaning: "student" },
      { word: "lesgeven", meaning: "to teach" },
      { word: "voorbeeld", meaning: "example" },
      { word: "huiswerk", meaning: "homework" },
      { word: "toets", meaning: "test" },
    ],
    name: "Education",
  },
  {
    words: [
      { word: "fiets", meaning: "bicycle" },
      { word: "bus", meaning: "bus" },
      { word: "tram", meaning: "tram" },
      { word: "rijden", meaning: "to drive/ride" },
      { word: "motorfiets", meaning: "motorcycle" },
      { word: "metro", meaning: "metro" },
      { word: "taxi", meaning: "taxi" },
      { word: "weg", meaning: "road" },
      { word: "verkeer", meaning: "traffic" },
      { word: "vrachtwagen", meaning: "truck" },
    ],
    name: "Traffic",
  },
  {
    words: [
      { word: "studeren", meaning: "to study" },
      { word: "praten", meaning: "to talk" },
      { word: "rennen", meaning: "to run" },
      { word: "wachten", meaning: "to wait" },
      { word: "kiezen", meaning: "to choose" },
      { word: "brengen", meaning: "to bring" },
      { word: "begrijpen", meaning: "to understand" },
      { word: "volgen", meaning: "to follow" },
      { word: "vragen", meaning: "to ask" },
      { word: "pakken", meaning: "to grab" },
    ],
    name: "Verbs: Present 3",
  },
  {
    words: [
      { word: "huwelijk", meaning: "marriage" },
      { word: "echtgenoot", meaning: "husband" },
      { word: "echtgenote", meaning: "wife" },
      { word: "gescheiden", meaning: "divorced" },
      { word: "getrouwd", meaning: "married" },
      { word: "bruiloft", meaning: "wedding" },
      { word: "pa", meaning: "dad" },
      { word: "ma", meaning: "mom" },
      { word: "opa", meaning: "grandpa" },
      { word: "oma", meaning: "grandma" },
    ],
    name: "Vocab???",
  },
  {
    words: [
      { word: "laten", meaning: "to let" },
      { word: "zien", meaning: "to see" },
      { word: "horen", meaning: "to hear" },
      { word: "blijven", meaning: "to stay" },
      { word: "moeten", meaning: "must/to have to" },
      { word: "willen", meaning: "to want" },
      { word: "kunnen", meaning: "to be able/can" },
    ],
    name: "Infinitives 2",
  },
  {
    words: [
      { word: "handel", meaning: "trade" },
      { word: "economisch", meaning: "economic" },
      { word: "economie", meaning: "economy" },
      { word: "vraag", meaning: "demand" },
      { word: "aanbod", meaning: "supply" },
      { word: "beurs", meaning: "stock exchange" },
      { word: "dollar", meaning: "dollar" },
      { word: "valuta", meaning: "currency" },
      { word: "winst", meaning: "profit" },
      { word: "budget", meaning: "budget" },
    ],
    name: "Economy",
  },
  {
    words: [
      { word: "genoeg", meaning: "enough" },
      { word: "iedereen", meaning: "everyone" },
      { word: "iemand", meaning: "someone" },
      { word: "iets", meaning: "something" },
      { word: "alles", meaning: "everything" },
      { word: "men", meaning: "one" },
      { word: "weinig", meaning: "few/little" },
      { word: "alle", meaning: "all (plural)" },
      { word: "veel", meaning: "many/a lot" },
      { word: "sommige", meaning: "some" },
    ],
    name: "Indefinite Pronouns",
  },
  {
    words: [
      { word: "me", meaning: "me" },
      { word: "je", meaning: "you" },
      { word: "zich", meaning: "oneself/himself/herself/themselves" },
      { word: "wassen", meaning: "to wash" },
      { word: "bewegen", meaning: "to move" },
      { word: "herinneren", meaning: "to remember" },
      { word: "ons", meaning: "us" },
      { word: "elkaar", meaning: "each other" },
      { word: "gedragen", meaning: "to behave" },
      { word: "haasten", meaning: "to hurry" },
    ],
    name: "Reflexives",
  },
  {
    words: [
      { word: "zaken", meaning: "business" },
      { word: "verzekering", meaning: "insurance" },
      { word: "bedrijf", meaning: "company" },
      { word: "fabriek", meaning: "factory" },
      { word: "klant", meaning: "customer" },
      { word: "eigenaar", meaning: "owner" },
      { word: "filiaal", meaning: "branch" },
      { word: "industrie", meaning: "industry" },
      { word: "belasting", meaning: "tax" },
      { word: "concurrentie", meaning: "competition" },
    ],
    name: "Business",
  },
  {
    words: [
      { word: "maat", meaning: "measure/size" },
      { word: "hoog", meaning: "high/tall" },
      { word: "grootte", meaning: "size" },
      { word: "lengte", meaning: "length" },
      { word: "laag", meaning: "low/short" },
      { word: "vorm", meaning: "shape" },
      { word: "cirkel", meaning: "circle" },
      { word: "driehoek", meaning: "triangle" },
      { word: "recht", meaning: "straight" },
      { word: "krom", meaning: "curved" },
    ],
    name: "Shapes & Sizes",
  },
  {
    words: [
      { word: "emotie", meaning: "emotion" },
      { word: "boos", meaning: "angry" },
      { word: "blij", meaning: "happy" },
      { word: "bang", meaning: "afraid" },
      { word: "huilen", meaning: "to cry" },
      { word: "lachen", meaning: "to laugh" },
      { word: "bezorgd", meaning: "worried" },
      { word: "verdrietig", meaning: "sad" },
      { word: "gevoel", meaning: "feeling" },
      { word: "trots", meaning: "proud" },
    ],
    name: "Feelings 1",
  },
  {
    words: [
      { word: "oorsprong", meaning: "origin" },
      { word: "actie", meaning: "action" },
      { word: "reactie", meaning: "reaction" },
      { word: "waarheid", meaning: "truth" },
      { word: "start", meaning: "start" },
      { word: "werkelijkheid", meaning: "reality" },
      { word: "gastvrijheid", meaning: "hospitality" },
      { word: "ellende", meaning: "misery" },
      { word: "gelegenheid", meaning: "occasion" },
      { word: "plezier", meaning: "pleasure" },
    ],
    name: "Abstract Nouns 2",
  },
  {
    words: [
      { word: "niet", meaning: "not" },
      { word: "nee", meaning: "no" },
      { word: "geen", meaning: "none/not any/no" },
    ],
    name: "Negatives 1",
  },
  {
    words: [
      { word: "graag gedaan", meaning: "you're welcome" },
      { word: "jammer", meaning: "too bad" },
      { word: "inderdaad", meaning: "indeed" },
      { word: "geen probleem", meaning: "no problem" },
      { word: "eet smakelijk", meaning: "enjoy your meal" },
      { word: "fijn", meaning: "nice/fine" },
      { word: "welkom", meaning: "welcome" },
      { word: "succes", meaning: "success" },
      { word: "prima", meaning: "fine/good" },
      { word: "vaarwel", meaning: "farewell" },
    ],
    name: "Phrases 2",
  },
  {
    words: [
      { word: "ploeg", meaning: "team" },
      { word: "speler", meaning: "player" },
      { word: "schoppen", meaning: "to kick" },
      { word: "springen", meaning: "to jump" },
      { word: "wedstrijd", meaning: "match/game" },
      { word: "gooien", meaning: "to throw" },
      { word: "doel", meaning: "goal" },
      { word: "punt", meaning: "point" },
      { word: "voetbal", meaning: "football/soccer" },
      { word: "scoren", meaning: "to score" },
    ],
    name: "Sports",
  },
  {
    words: [
      { word: "douche", meaning: "shower" },
      { word: "toilet", meaning: "toilet" },
      { word: "kraan", meaning: "tap/faucet" },
      { word: "gootsteen", meaning: "sink" },
      { word: "handdoek", meaning: "towel" },
      { word: "bad", meaning: "bath" },
      { word: "shampoo", meaning: "shampoo" },
      { word: "droog", meaning: "dry" },
      { word: "nat", meaning: "wet" },
      { word: "zeep", meaning: "soap" },
    ],
    name: "Bathroom",
  },
  {
    words: [
      { word: "gaan", meaning: "to go" },
      { word: "zullen", meaning: "will/shall" },
      { word: "veranderen", meaning: "to change" },
      { word: "kiezen", meaning: "to choose" },
      { word: "breken", meaning: "to break" },
      { word: "regenen", meaning: "to rain" },
      { word: "verliezen", meaning: "to lose" },
      { word: "overmorgen", meaning: "the day after tomorrow" },
      { word: "winnen", meaning: "to win" },
      { word: "ooit", meaning: "ever/someday" },
    ],
    name: "Future verbs",
  },
  {
    words: [
      { word: "bloem", meaning: "flower" },
      { word: "tulp", meaning: "tulip" },
      { word: "gras", meaning: "grass" },
      { word: "natuur", meaning: "nature" },
      { word: "plant", meaning: "plant" },
      { word: "groeien", meaning: "to grow" },
      { word: "land", meaning: "land" },
      { word: "leven", meaning: "life" },
      { word: "gewas", meaning: "crop" },
      { word: "zand", meaning: "sand" },
    ],
    name: "Nature",
  },
  {
    words: [
      { word: "maandag", meaning: "Monday" },
      { word: "zondag", meaning: "Sunday" },
      { word: "zaterdag", meaning: "Saturday" },
      { word: "donderdag", meaning: "Thursday" },
      { word: "vrijdag", meaning: "Friday" },
      { word: "woensdag", meaning: "Wednesday" },
      { word: "dinsdag", meaning: "Tuesday" },
      { word: "week", meaning: "week" },
      { word: "jaar", meaning: "year" },
      { word: "weekend", meaning: "weekend" },
    ],
    name: "Time",
  },
  {
    words: [
      { word: "kijken", meaning: "to look" },
      { word: "oog", meaning: "eye" },
      { word: "lijken", meaning: "to seem" },
      { word: "foto", meaning: "photo" },
      { word: "bekijken", meaning: "to view" },
      { word: "uitzicht", meaning: "view" },
      { word: "luisteren", meaning: "to listen" },
      { word: "muziek", meaning: "music" },
      { word: "geluid", meaning: "sound" },
      { word: "oor", meaning: "ear" },
    ],
    name: "Senses",
  },
  {
    words: [
      { word: "normaal", meaning: "normal" },
      { word: "mogelijk", meaning: "possible" },
      { word: "perfect", meaning: "perfect" },
      { word: "tenminste", meaning: "at least" },
      { word: "nauwelijks", meaning: "hardly/barely" },
      { word: "tegelijk", meaning: "at the same time" },
      { word: "momenteel", meaning: "currently" },
      { word: "voldoende", meaning: "sufficient/enough" },
      { word: "echter", meaning: "however" },
      { word: "zeer", meaning: "very" },
    ],
    name: "Adverbs 2",
  },
  {
    words: [
      { word: "erin", meaning: "in it/into it" },
      { word: "erop", meaning: "on it/onto it" },
      { word: "ermee", meaning: "with it" },
      { word: "ernaar", meaning: "towards it/to it" },
      { word: "ernaast", meaning: "next to it/beside it" },
      { word: "er-", meaning: "prefix indicating location" },
      { word: "eruit", meaning: "out of it" },
      { word: "ertussen", meaning: "between them" },
      { word: "ervandaan", meaning: "from there (away from it)" },
      { word: "erheen", meaning: "to there/to it" },
    ],
    name: "Pronominal Adverbs",
  },
  {
    words: [
      { word: "kan", meaning: "can" },
      { word: "kunt", meaning: "can (you)" },
      { word: "willen", meaning: "to want" },
      { word: "wil", meaning: "wants" },
      { word: "kunnen", meaning: "to be able/can" },
      { word: "mag", meaning: "may/can" },
      { word: "moeten", meaning: "must/to have to" },
      { word: "mogen", meaning: "may/to be allowed to" },
      { word: "blijven", meaning: "to stay" },
      { word: "komen", meaning: "to come" },
    ],
    name: "Modal verbs",
  },
  {
    words: [
      { word: "god", meaning: "god" },
      { word: "godin", meaning: "goddess" },
      { word: "bidden", meaning: "to pray" },
      { word: "religie", meaning: "religion" },
      { word: "geloof", meaning: "faith" },
      { word: "gelovig", meaning: "faithful" },
      { word: "gebed", meaning: "prayer" },
      { word: "geest", meaning: "spirit" },
      { word: "ziel", meaning: "soul" },
      { word: "priesteres", meaning: "priestess" },
    ],
    name: "Spiritual & Religion",
  },
  {
    words: [
      { word: "u", meaning: "you (formal)" },
      { word: "uw", meaning: "your (formal)" },
      { word: "alstublieft", meaning: "please" },
      { word: "meneer", meaning: "mister/sir" },
      { word: "mevrouw", meaning: "madam/mrs" },
      { word: "dank u wel", meaning: "thank you very much" },
    ],
    name: "Formal",
  },
  {
    words: [
      { word: "eenentwintig", meaning: "twenty-one" },
      { word: "tweeëntwintig", meaning: "twenty-two" },
      { word: "drieëntwintig", meaning: "twenty-three" },
      { word: "vierentwintig", meaning: "twenty-four" },
      { word: "vijfentwintig", meaning: "twenty-five" },
      { word: "zesentwintig", meaning: "twenty-six" },
      { word: "zevenentwintig", meaning: "twenty-seven" },
      { word: "achtentwintig", meaning: "twenty-eight" },
      { word: "negenentwintig", meaning: "twenty-nine" },
      { word: "dertig", meaning: "thirty" },
    ],
    name: "Numbers 2",
  },
  {
    words: [
      { word: "wie", meaning: "who" },
      { word: "waar", meaning: "where" },
      { word: "wat", meaning: "what" },
      { word: "waarom", meaning: "why" },
      { word: "hoe", meaning: "how" },
      { word: "wiens", meaning: "whose" },
      { word: "welk", meaning: "which (neuter)" },
      { word: "welke", meaning: "which (common)" },
      { word: "hoeveel", meaning: "how much/how many" },
      { word: "wanneer", meaning: "when" },
    ],
    name: "Questions",
  },
  {
    words: [
      { word: "aantekening", meaning: "note" },
      { word: "cursus", meaning: "course" },
      { word: "aanmelding", meaning: "registration" },
      { word: "universiteit", meaning: "university" },
      { word: "lezing", meaning: "lecture" },
      { word: "professor", meaning: "professor" },
      { word: "verslag", meaning: "report" },
      { word: "programma", meaning: "program" },
      { word: "college", meaning: "college" },
      { word: "document", meaning: "document" },
    ],
    name: "University",
  },
  {
    words: [
      { word: "nu", meaning: "now" },
      { word: "soms", meaning: "sometimes" },
      { word: "daar", meaning: "there" },
      { word: "hier", meaning: "here" },
      { word: "misschien", meaning: "maybe" },
    ],
    name: "Inversion",
  },
  {
    words: [
      { word: "verkiezing", meaning: "election" },
      { word: "kiezer", meaning: "voter" },
      { word: "lid", meaning: "member" },
      { word: "stemmen", meaning: "to vote" },
      { word: "partij", meaning: "party" },
      { word: "leden", meaning: "members" },
      { word: "eisen", meaning: "requirements/demands" },
      { word: "kandidaat", meaning: "candidate" },
      { word: "campagne", meaning: "campaign" },
      { word: "regel", meaning: "rule" },
    ],
    name: "Politics",
  },
  {
    words: [
      { word: "om", meaning: "around" },
      { word: "te", meaning: "to" },
      { word: "zonder", meaning: "without" },
      { word: "door", meaning: "through" },
      { word: "pronouns", meaning: "pronouns" },
      { word: "vragen om", meaning: "to ask for" },
      { word: "beginnen", meaning: "to begin" },
      { word: "proberen", meaning: "to try" },
      { word: "vergeten", meaning: "to forget" },
      { word: "leren", meaning: "to learn" },
    ],
    name: "Te + infinitive verbs",
  },
  {
    words: [
      { word: "schoonheid", meaning: "beauty" },
      { word: "vrijheid", meaning: "freedom" },
      { word: "eerlijkheid", meaning: "honesty" },
      { word: "verantwoordelijkheid", meaning: "responsibility" },
      { word: "mogelijkheid", meaning: "possibility" },
      { word: "moeilijkheid", meaning: "difficulty" },
      { word: "beweging", meaning: "movement" },
      { word: "verandering", meaning: "change" },
      { word: "bestelling", meaning: "order" },
      { word: "opening", meaning: "opening" },
    ],
    name: "Suffixes",
  },
  {
    words: [
      { word: "strand", meaning: "beach" },
      { word: "stad", meaning: "city" },
      { word: "gebouw", meaning: "building" },
      { word: "hotel", meaning: "hotel" },
      { word: "steden", meaning: "cities" },
      { word: "restaurant", meaning: "restaurant" },
      { word: "adres", meaning: "address" },
      { word: "route", meaning: "route" },
      { word: "straat", meaning: "street" },
      { word: "dorp", meaning: "village" },
    ],
    name: "Places",
  },
  {
    words: [
      { word: "omhoog", meaning: "upwards/up" },
      { word: "omlaag", meaning: "downwards/down" },
      { word: "vooruit", meaning: "forward/ahead" },
      { word: "achteruit", meaning: "backward/behind" },
      { word: "links", meaning: "left" },
      { word: "rechts", meaning: "right" },
      { word: "rechtsaf", meaning: "to the right" },
      { word: "rechtdoor", meaning: "straight ahead" },
      { word: "afslaan", meaning: "to turn" },
      { word: "linksaf", meaning: "to the left" },
    ],
    name: "Directions",
  },
  {
    words: [
      { word: "eten", meaning: "to eat" },
      { word: "boterham", meaning: "sandwich" },
      { word: "drinken", meaning: "to drink" },
      { word: "rijst", meaning: "rice" },
      { word: "jullie", meaning: "you (plural)" },
      { word: "we", meaning: "we" },
      { word: "vrouwen", meaning: "women" },
      { word: "lezen", meaning: "to read" },
      { word: "de", meaning: "the" },
      { word: "mannen", meaning: "men" },
    ],
    name: "Basics 2",
  },
  {
    words: [
      { word: "hebben", meaning: "to have" },
      { word: "gisteren", meaning: "yesterday" },
      { word: "gespeeld", meaning: "played" },
      { word: "geregend", meaning: "rained" },
      { word: "gewerkt", meaning: "worked" },
      { word: "geluisterd", meaning: "listened" },
      { word: "gekookt", meaning: "cooked" },
      { word: "gevraagd", meaning: "asked" },
      { word: "gewacht", meaning: "waited" },
      { word: "gezet", meaning: "put" },
    ],
    name: "Present Perfect: Regular/Weak Verbs",
  },
  {
    words: [
      { word: "betaald", meaning: "paid" },
      { word: "gebeurd", meaning: "happened" },
      { word: "gebleven", meaning: "stayed" },
      { word: "geopend", meaning: "opened" },
      { word: "vertrokken", meaning: "departed/left" },
      { word: "eergisteren", meaning: "the day before yesterday" },
      { word: "genomen", meaning: "taken" },
      { word: "gesproken", meaning: "spoken" },
      { word: "verkocht", meaning: "sold" },
      { word: "bezocht", meaning: "visited" },
    ],
    name: "Verbs: Present Perfect",
  },
  {
    words: [
      { word: "vis", meaning: "fish" },
      { word: "wijn", meaning: "wine" },
      { word: "thee", meaning: "tea" },
      { word: "koffie", meaning: "coffee" },
      { word: "ei", meaning: "egg" },
      { word: "kip", meaning: "chicken" },
      { word: "suiker", meaning: "sugar" },
      { word: "middageten", meaning: "lunch" },
      { word: "ontbijt", meaning: "breakfast" },
      { word: "kaas", meaning: "cheese" },
    ],
    name: "Eten",
  },
  {
    words: [
      { word: "patiënt", meaning: "patient" },
      { word: "gezond", meaning: "healthy" },
      { word: "ongeluk", meaning: "accident" },
      { word: "zorg", meaning: "care" },
      { word: "medicijn", meaning: "medicine" },
      { word: "ziek", meaning: "sick" },
      { word: "behandeling", meaning: "treatment" },
      { word: "pijn", meaning: "pain" },
      { word: "gezondheid", meaning: "health" },
      { word: "ziekte", meaning: "illness/disease" },
    ],
    name: "Medical",
  },
  {
    words: [
      { word: "bouwen", meaning: "to build" },
      { word: "dak", meaning: "roof" },
      { word: "lift", meaning: "elevator/lift" },
      { word: "verdieping", meaning: "floor/story" },
      { word: "trap", meaning: "stairs" },
      { word: "plafond", meaning: "ceiling" },
      { word: "uitgang", meaning: "exit" },
      { word: "ingang", meaning: "entrance" },
      { word: "gang", meaning: "corridor/hallway" },
      { word: "balkon", meaning: "balcony" },
    ],
    name: "Buildings",
  },
  {
    words: [
      { word: "hand", meaning: "hand" },
      { word: "lichaam", meaning: "body" },
      { word: "hoofd", meaning: "head" },
      { word: "bloed", meaning: "blood" },
      { word: "zorgen", meaning: "to worry/take care of" },
      { word: "haar", meaning: "hair/her" },
      { word: "hart", meaning: "heart" },
      { word: "huid", meaning: "skin" },
      { word: "nek", meaning: "neck" },
      { word: "gezicht", meaning: "face" },
    ],
    name: "Medical",
  },
  {
    words: [
      { word: "machine", meaning: "machine" },
      { word: "batterij", meaning: "battery" },
      { word: "televisie", meaning: "television" },
      { word: "gereedschap", meaning: "tool" },
      { word: "radio", meaning: "radio" },
      { word: "apparaat", meaning: "device/appliance" },
      { word: "stopcontact", meaning: "outlet/socket" },
      { word: "rekenmachine", meaning: "calculator" },
      { word: "stekker", meaning: "plug" },
      { word: "knop", meaning: "button" },
    ],
    name: "Technology",
  },
  {
    words: [
      { word: "beroemd", meaning: "famous" },
      { word: "algemeen", meaning: "general" },
      { word: "fantastisch", meaning: "fantastic" },
      { word: "onmogelijk", meaning: "impossible" },
      { word: "mogelijk", meaning: "possible" },
      { word: "belgisch", meaning: "Belgian" },
      { word: "serieus", meaning: "serious" },
      { word: "uitstekend", meaning: "excellent" },
      { word: "beschikbaar", meaning: "available" },
      { word: "bloot", meaning: "naked/bare" },
    ],
    name: "Adjectives 3",
  },
  {
    words: [
      { word: "man", meaning: "man" },
      { word: "vrouw", meaning: "woman" },
      { word: "ik", meaning: "I" },
      { word: "ben", meaning: "am" },
      { word: "jongen", meaning: "boy" },
      { word: "een", meaning: "a/an" },
      { word: "en", meaning: "and" },
      { word: "is", meaning: "is" },
      { word: "ze", meaning: "she" },
      { word: "of", meaning: "or" },
    ],
    name: "Basics 1",
  },
  {
    words: [
      { word: "zon", meaning: "sun" },
      { word: "weer", meaning: "weather" },
      { word: "regen", meaning: "rain" },
      { word: "wind", meaning: "wind" },
      { word: "storm", meaning: "storm" },
      { word: "schijnen", meaning: "to shine" },
      { word: "wolk", meaning: "cloud" },
      { word: "mist", meaning: "mist/fog" },
      { word: "regenboog", meaning: "rainbow" },
      { word: "sneeuw", meaning: "snow" },
    ],
    name: "Weather",
  },
  {
    words: [
      { word: "kat", meaning: "cat" },
      { word: "dier", meaning: "animal" },
      { word: "hond", meaning: "dog" },
      { word: "vogel", meaning: "bird" },
      { word: "muis", meaning: "mouse" },
      { word: "mens", meaning: "human" },
      { word: "olifant", meaning: "elephant" },
      { word: "eend", meaning: "duck" },
      { word: "schildpad", meaning: "turtle" },
      { word: "paard", meaning: "horse" },
    ],
    name: "Dieren",
  },
  {
    words: [
      { word: "nu", meaning: "now" },
      { word: "soms", meaning: "sometimes" },
      { word: "daar", meaning: "there" },
      { word: "hier", meaning: "here" },
      { word: "misschien", meaning: "maybe/perhaps" },
    ],
    name: "No Inversion",
  },
  {
    words: [
      { word: "net", meaning: "just/recently" },
      { word: "gegeten", meaning: "eaten" },
      { word: "gezien", meaning: "seen" },
      { word: "gelezen", meaning: "read" },
      { word: "geschreven", meaning: "written" },
      { word: "gekomen", meaning: "come/arrived" },
      { word: "geslapen", meaning: "slept" },
      { word: "gestaan", meaning: "stood" },
      { word: "nadat", meaning: "after" },
      { word: "geweest", meaning: "been" },
    ],
    name: "Present Perfect: Strong Verbs",
  },
  {
    words: [
      { word: "was", meaning: "was" },
      { word: "waren", meaning: "were" },
      { word: "had", meaning: "had" },
      { word: "hadden", meaning: "had (plural)" },
      { word: "deed", meaning: "did" },
      { word: "deden", meaning: "did (plural)" },
      { word: "willen", meaning: "want" },
      { word: "spelen", meaning: "to play" },
      { word: "toen", meaning: "then" },
      { word: "horen", meaning: "to hear" },
    ],
    name: "Simple Past 1",
  },
  {
    words: [
      { word: "oostelijk", meaning: "eastern" },
      { word: "westelijk", meaning: "western" },
      { word: "halfrond", meaning: "hemisphere" },
      { word: "noordelijk", meaning: "northern" },
      { word: "zuidelijk", meaning: "southern" },
      { word: "ontdekken", meaning: "to discover" },
      { word: "europa", meaning: "Europe" },
      { word: "azië", meaning: "Asia" },
      { word: "afrika", meaning: "Africa" },
      { word: "noord-amerika", meaning: "North America" },
    ],
    name: "Mapping the world: Geography",
  },
  {
    words: [
      { word: "bioscoop", meaning: "cinema" },
      { word: "film", meaning: "film/movie" },
      { word: "festival", meaning: "festival" },
      { word: "toneel", meaning: "theater" },
      { word: "concert", meaning: "concert" },
      { word: "band", meaning: "band (music)" },
      { word: "kasteel", meaning: "castle" },
      { word: "toren", meaning: "tower" },
      { word: "museum", meaning: "museum" },
      { word: "pretpark", meaning: "amusement park" },
    ],
    name: "Leisure",
  },
  {
    words: [
      { word: "gebruikt", meaning: "used" },
      { word: "toegevoegd", meaning: "added" },
      { word: "gekookt", meaning: "cooked" },
      { word: "geleend", meaning: "borrowed" },
      { word: "beschermd", meaning: "protected" },
      { word: "vertaald", meaning: "translated" },
      { word: "on-", meaning: "un-" },
      { word: "gelezen", meaning: "read" },
      { word: "gestolen", meaning: "stolen" },
      { word: "deelwoorden", meaning: "past participles" },
    ],
    name: "Past Participle",
  },
  {
    words: [
      { word: "staan", meaning: "to stand" },
      { word: "denken", meaning: "to think" },
      { word: "zeggen", meaning: "to say" },
      { word: "werken", meaning: "to work" },
      { word: "heten", meaning: "to be called/named" },
      { word: "leren", meaning: "to learn" },
      { word: "helpen", meaning: "to help" },
      { word: "nodig hebben", meaning: "to need" },
      { word: "gebruiken", meaning: "to use" },
      { word: "kopen", meaning: "to buy" },
    ],
    name: "Verbs: Present 2",
  },
  {
    words: [
      {
        word: "pakjesavond",
        meaning: "gift-giving evening (Sinterklaas tradition)",
      },
      { word: "sinterklaas", meaning: "Sinterklaas (St. Nicholas)" },
      { word: "oudejaarsavond", meaning: "New Year's Eve" },
      { word: "nieuwjaar", meaning: "New Year" },
      { word: "vieren", meaning: "to celebrate" },
      { word: "cadeau", meaning: "gift/present" },
      { word: "pasen", meaning: "Easter" },
      { word: "kerstmis", meaning: "Christmas" },
      { word: "koningsdag", meaning: "King's Day" },
      { word: "traditie", meaning: "tradition" },
    ],
    name: "Holidays",
  },
  {
    words: [
      { word: "dat", meaning: "that" },
      { word: "wie", meaning: "who" },
      { word: "waar", meaning: "where" },
      { word: "wat", meaning: "what" },
      { word: "die", meaning: "that/those" },
      { word: "degene", meaning: "the one (he/she/it)" },
      { word: "van wie", meaning: "whose" },
      { word: "diegene", meaning: "the one (he/she/it)" },
      { word: "wiens", meaning: "whose" },
      { word: "datgene", meaning: "that which" },
    ],
    name: "Pronouns relative",
  },
  {
    words: [
      { word: "zitten", meaning: "to sit" },
      { word: "doos", meaning: "box" },
      { word: "auto", meaning: "car" },
      { word: "mand", meaning: "basket" },
      { word: "in", meaning: "in" },
      { word: "liggen", meaning: "to lie" },
      { word: "amsterdam", meaning: "Amsterdam" },
      { word: "deken", meaning: "blanket" },
      { word: "bal", meaning: "ball" },
      { word: "park", meaning: "park" },
    ],
    name: "Staan/Liggen/Zitten",
  },
  {
    words: [
      { word: "maar", meaning: "but" },
      { word: "want", meaning: "because" },
      { word: "of", meaning: "or" },
      { word: "dus", meaning: "so" },
      { word: "en", meaning: "and" },
    ],
    name: "Conjunctions 1: Coordinating",
  },
  {
    words: [
      { word: "wetenschap", meaning: "science" },
      { word: "onderzoek", meaning: "research" },
      { word: "laboratorium", meaning: "laboratory" },
      { word: "theorie", meaning: "theory" },
      { word: "experiment", meaning: "experiment" },
      { word: "uitvoeren", meaning: "to conduct/perform" },
      { word: "methode", meaning: "method" },
      { word: "wetenschappelijk", meaning: "scientific" },
      { word: "formule", meaning: "formula" },
      { word: "definitie", meaning: "definition" },
    ],
    name: "Science",
  },
  {
    words: [
      { word: "eenheid", meaning: "unit" },
      { word: "snelheid", meaning: "speed" },
      { word: "afstand", meaning: "distance" },
      { word: "liter", meaning: "liter" },
      { word: "massa", meaning: "mass" },
      { word: "kilogram", meaning: "kilogram" },
      { word: "bedragen", meaning: "to amount" },
      { word: "diepte", meaning: "depth" },
      { word: "meten", meaning: "to measure" },
      { word: "hoogte", meaning: "height" },
    ],
    name: "Science! 2",
  },
  {
    words: [
      { word: "zouden", meaning: "would" },
      { word: "zou", meaning: "would" },
      { word: "moeten", meaning: "must/should" },
      { word: "veranderen", meaning: "to change" },
      { word: "doen", meaning: "to do" },
      { word: "kiezen", meaning: "to choose" },
      { word: "willen", meaning: "to want" },
      { word: "vinden", meaning: "to find" },
      { word: "eten", meaning: "to eat" },
      { word: "was", meaning: "was" },
    ],
    name: "The Conditional",
  },
  {
    words: [
      { word: "politie", meaning: "police" },
      { word: "taak", meaning: "task" },
      { word: "beschermen", meaning: "to protect" },
      { word: "hulp", meaning: "help/assistance" },
      { word: "bellen", meaning: "to call" },
      { word: "politieagent", meaning: "police officer" },
      { word: "arrestatie", meaning: "arrest" },
      { word: "misdaad", meaning: "crime" },
      { word: "plegen", meaning: "to commit" },
      { word: "stelen", meaning: "to steal" },
    ],
    name: "Services",
  },
  {
    words: [
      { word: "euro", meaning: "euro" },
      { word: "cent", meaning: "cent" },
      { word: "kosten", meaning: "costs" },
      { word: "verkopen", meaning: "to sell" },
      { word: "winkel", meaning: "shop/store" },
      { word: "te koop", meaning: "for sale" },
      { word: "gratis", meaning: "free" },
      { word: "supermarkt", meaning: "supermarket" },
      { word: "boodschappen", meaning: "groceries" },
      { word: "slagerij", meaning: "butcher shop" },
    ],
    name: "Shopping",
  },
  {
    words: [
      { word: "had", meaning: "had" },
      { word: "hadden", meaning: "had (plural)" },
      { word: "gehoord", meaning: "heard" },
      { word: "verwacht", meaning: "expected" },
      { word: "besloten", meaning: "decided" },
      { word: "gezien", meaning: "seen" },
      { word: "geprobeerd", meaning: "tried" },
      { word: "geroepen", meaning: "called" },
      { word: "verloren", meaning: "lost" },
      { word: "gebeld", meaning: "called (by phone)" },
    ],
    name: "The past perfect/pluperfect",
  },
  {
    words: [
      { word: "dit", meaning: "this" },
      { word: "die", meaning: "that" },
      { word: "dat", meaning: "that" },
      { word: "deze", meaning: "these" },
      { word: "beide", meaning: "both" },
      { word: "zo'n", meaning: "such a" },
      { word: "zulke", meaning: "such (plural)" },
      { word: "zulk", meaning: "such (singular)" },
      { word: "al", meaning: "already" },
      { word: "zoiets", meaning: "something like that" },
    ],
    name: "Determiners",
  },
  {
    words: [
      { word: "maan", meaning: "moon" },
      { word: "aarde", meaning: "earth" },
      { word: "draaien", meaning: "to rotate/turn" },
      { word: "rond", meaning: "around" },
      { word: "ruimte", meaning: "space" },
      { word: "ster", meaning: "star" },
      { word: "zonnestelsel", meaning: "solar system" },
      { word: "planeet", meaning: "planet" },
      { word: "sterrenkunde", meaning: "astronomy" },
      { word: "universum", meaning: "universe" },
    ],
    name: "Space",
  },
  {
    words: [
      { word: "briefje", meaning: "note/paper" },
      { word: "doosje", meaning: "box" },
      { word: "huisje", meaning: "house" },
      { word: "mandje", meaning: "basket" },
      { word: "lampje", meaning: "lamp" },
      { word: "kastje", meaning: "cabinet" },
      { word: "mannetje", meaning: "little man" },
      { word: "blaadje", meaning: "leaf" },
      { word: "vrouwtje", meaning: "little woman" },
      { word: "raampje", meaning: "window (small)" },
    ],
    name: "Diminutives",
  },
  {
    words: [
      { word: "reizen", meaning: "to travel" },
      { word: "reist", meaning: "travels" },
      { word: "reis", meaning: "journey/trip" },
      { word: "amerika", meaning: "America" },
      { word: "frankrijk", meaning: "France" },
      { word: "duitsland", meaning: "Germany" },
      { word: "buitenland", meaning: "abroad/foreign country" },
      { word: "vlucht", meaning: "flight" },
      { word: "boeken", meaning: "to book" },
      { word: "koffer", meaning: "suitcase" },
    ],
    name: "Travel",
  },
  {
    words: [
      { word: "romantisch", meaning: "romantic" },
      { word: "passie", meaning: "passion" },
      { word: "kussen", meaning: "to kiss" },
      { word: "relatie", meaning: "relationship" },
      { word: "knuffelen", meaning: "to hug/cuddle" },
      { word: "liefde", meaning: "love" },
      { word: "verkering", meaning: "courtship/dating" },
      { word: "hetero", meaning: "heterosexual" },
      { word: "homo", meaning: "homosexual" },
      { word: "aantrekkelijk", meaning: "attractive" },
    ],
    name: "Romance & Relationships",
  },
  {
    words: [
      { word: "goed", meaning: "good" },
      { word: "rustig", meaning: "calm/quiet" },
      { word: "al", meaning: "already" },
      { word: "snel", meaning: "fast/quick" },
      { word: "langzaam", meaning: "slow" },
      { word: "dan", meaning: "then" },
      { word: "ook", meaning: "also" },
      { word: "nog", meaning: "still/yet" },
      { word: "heel", meaning: "very" },
      { word: "steeds", meaning: "still/continuously" },
    ],
    name: "Adverbs",
  },
  {
    words: [
      { word: "loop", meaning: "I walk" },
      { word: "loopt", meaning: "he/she/it walks" },
      { word: "lopen", meaning: "to walk" },
      { word: "schrijf", meaning: "I write" },
      { word: "schrijft", meaning: "he/she/it writes" },
      { word: "schrijven", meaning: "to write" },
      { word: "zwemmen", meaning: "to swim" },
      { word: "zwemt", meaning: "he/she/it swims" },
      { word: "zwem", meaning: "I swim" },
      { word: "koken", meaning: "to cook" },
    ],
    name: "Verbs: Present",
  },
  {
    words: [
      { word: "vla", meaning: "custard/pudding" },
      { word: "hagelslag", meaning: "chocolate sprinkles" },
      { word: "appelflap", meaning: "apple turnover/pastry" },
      { word: "poffertje", meaning: "small Dutch pancake" },
      { word: "stroopwafel", meaning: "syrup waffle" },
      { word: "drop", meaning: "liquorice" },
      { word: "vlaai", meaning: "fruit pie/tart" },
      { word: "kroket", meaning: "croquette" },
      { word: "café", meaning: "cafe" },
      { word: "bakje troost", meaning: "cup of comfort (coffee)" },
    ],
    name: "Dutch Food and Snacks",
  },
  {
    words: [
      { word: "duits", meaning: "German" },
      { word: "frans", meaning: "French" },
      { word: "portugees", meaning: "Portuguese" },
      { word: "spaans", meaning: "Spanish" },
      { word: "russisch", meaning: "Russian" },
      { word: "chinees", meaning: "Chinese" },
      { word: "taal", meaning: "language" },
      { word: "hebreeuws", meaning: "Hebrew" },
      { word: "arabisch", meaning: "Arabic" },
      { word: "fries", meaning: "Frisian" },
    ],
    name: "Language",
  },
  {
    words: [
      { word: "meer", meaning: "lake" },
      { word: "land", meaning: "land/country" },
      { word: "eiland", meaning: "island" },
      { word: "bos", meaning: "forest" },
      { word: "zee", meaning: "sea" },
      { word: "rivier", meaning: "river" },
      { word: "berg", meaning: "mountain" },
      { word: "landschap", meaning: "landscape" },
      { word: "woestijn", meaning: "desert" },
      { word: "kust", meaning: "coast" },
    ],
    name: "Geography",
  },
  {
    words: [
      { word: "verkouden", meaning: "having a cold" },
      { word: "doof", meaning: "deaf" },
      { word: "niezen", meaning: "to sneeze" },
      { word: "hoesten", meaning: "to cough" },
      { word: "blind", meaning: "blind" },
      { word: "overgeven", meaning: "to vomit" },
      { word: "dodelijk", meaning: "fatal/deadly" },
      { word: "giftig", meaning: "poisonous" },
      { word: "duizelig", meaning: "dizzy" },
      { word: "hoofdpijn", meaning: "headache" },
    ],
    name: "Medical",
  },
  {
    words: [
      { word: "haar", meaning: "her" },
      { word: "hem", meaning: "him" },
      { word: "mij", meaning: "me" },
      { word: "me", meaning: "me" },
      { word: "het", meaning: "it" },
      { word: "jou", meaning: "you (singular)" },
      { word: "ons", meaning: "us" },
      { word: "je", meaning: "you (singular)" },
      { word: "ze", meaning: "they/she" },
      { word: "hun", meaning: "their/them" },
    ],
    name: "Objective pronouns",
  },
  {
    words: [
      { word: "metaal", meaning: "metal" },
      { word: "zilver", meaning: "silver" },
      { word: "ijzer", meaning: "iron" },
      { word: "hout", meaning: "wood" },
      { word: "goud", meaning: "gold" },
      { word: "plastic", meaning: "plastic" },
      { word: "katoen", meaning: "cotton" },
      { word: "wol", meaning: "wool" },
      { word: "zijde", meaning: "silk" },
      { word: "leer", meaning: "leather" },
    ],
    name: "Materials",
  },
  {
    words: [
      { word: "wanneer", meaning: "when" },
      { word: "als", meaning: "if" },
      { word: "hoewel", meaning: "although" },
      { word: "tenzij", meaning: "unless" },
      { word: "dat", meaning: "that" },
      { word: "zodat", meaning: "so that" },
      { word: "terwijl", meaning: "while" },
      { word: "totdat", meaning: "until" },
      { word: "of", meaning: "or" },
      { word: "omdat", meaning: "because" },
    ],
    name: "Conjunctions",
  },
  {
    words: [
      { word: "eng", meaning: "scary" },
      { word: "echt", meaning: "real" },
      { word: "saai", meaning: "boring" },
      { word: "rijk", meaning: "rich" },
      { word: "arm", meaning: "poor" },
      { word: "verkeerd", meaning: "wrong" },
      { word: "voorzichtig", meaning: "careful" },
      { word: "gevaarlijk", meaning: "dangerous" },
      { word: "favoriet", meaning: "favorite" },
      { word: "raar", meaning: "strange/weird" },
    ],
    name: "Adjectives 2",
  },
  {
    words: [
      { word: "in", meaning: "in" },
      { word: "naar", meaning: "to" },
      { word: "op", meaning: "on" },
      { word: "nederland", meaning: "Netherlands" },
      { word: "wonen", meaning: "to live" },
      { word: "belgië", meaning: "Belgium" },
      { word: "voor", meaning: "for" },
      { word: "naast", meaning: "next to/beside" },
      { word: "uit", meaning: "out of/from" },
      { word: "met", meaning: "with" },
    ],
    name: "Prepositions",
  },
  {
    words: [
      { word: "nooit", meaning: "never" },
      { word: "niemand", meaning: "nobody" },
      { word: "niets", meaning: "nothing" },
      { word: "nergens", meaning: "nowhere" },
      { word: "noch", meaning: "nor" },
      { word: "niks", meaning: "nothing" },
      { word: "meer", meaning: "more" },
      { word: "nog niet", meaning: "not yet" },
      { word: "helemaal niet", meaning: "not at all" },
      { word: "geen enkel", meaning: "not a single" },
    ],
    name: "Negatives 2",
  },
  {
    words: [
      { word: "at", meaning: "ate" },
      { word: "aten", meaning: "ate" },
      { word: "sprak", meaning: "spoke" },
      { word: "drinken", meaning: "to drink" },
      { word: "spraken", meaning: "spoke" },
      { word: "lopen", meaning: "to walk" },
      { word: "liggen", meaning: "to lie (down)" },
      { word: "zag", meaning: "saw" },
      { word: "zagen", meaning: "saw" },
      { word: "zeiden", meaning: "said" },
    ],
    name: "Verbs Past: 1",
  },
  {
    words: [
      { word: "kapsel", meaning: "hairstyle" },
      { word: "baard", meaning: "beard" },
      { word: "kaal", meaning: "bald" },
      { word: "snor", meaning: "mustache" },
      { word: "blond", meaning: "blonde" },
      { word: "uiterlijk", meaning: "appearance" },
      { word: "veter", meaning: "shoelace" },
      { word: "rits", meaning: "zipper" },
      { word: "knap", meaning: "handsome" },
      { word: "knoop", meaning: "button/knot" },
    ],
    name: "Appearance 2",
  },
  {
    words: [
      { word: "samenleving", meaning: "society" },
      { word: "cultuur", meaning: "culture" },
      { word: "stichting", meaning: "foundation" },
      { word: "gemeenschap", meaning: "community" },
      { word: "armoede", meaning: "poverty" },
      { word: "welvaart", meaning: "prosperity" },
      { word: "gelijkheid", meaning: "equality" },
      { word: "samenwerking", meaning: "cooperation" },
      { word: "chaos", meaning: "chaos" },
      { word: "vooruitgang", meaning: "progress" },
    ],
    name: "Society",
  },
  {
    words: [
      { word: "zijn", meaning: "his / its / their" },
      { word: "mijn", meaning: "my" },
      { word: "onze", meaning: "our" },
      { word: "hun", meaning: "their" },
      { word: "jouw", meaning: "your (informal, singular)" },
      { word: "haar", meaning: "her" },
      { word: "van", meaning: "of" },
      { word: "naam", meaning: "name" },
      { word: "jou", meaning: "you (informal, singular)" },
      { word: "ons", meaning: "our" },
    ],
    name: "Possessives",
  },
  {
    words: [
      { word: "burger", meaning: "citizen" },
      { word: "bevolking", meaning: "population" },
      { word: "buur", meaning: "neighbor" },
      { word: "persoon", meaning: "person" },
      { word: "jeugd", meaning: "youth" },
      { word: "groep", meaning: "group" },
      { word: "dame", meaning: "lady" },
      { word: "koppel", meaning: "couple" },
      { word: "volwassene", meaning: "adult" },
      { word: "heer", meaning: "gentleman" },
    ],
    name: "People",
  },
  {
    words: [
      { word: "groningen", meaning: "Groningen" },
      { word: "provincie", meaning: "province" },
      { word: "utrecht", meaning: "Utrecht" },
      { word: "gracht", meaning: "canal" },
      { word: "rotterdam", meaning: "Rotterdam" },
      { word: "friesland", meaning: "Friesland" },
      { word: "dijk", meaning: "dike" },
      { word: "limburg", meaning: "Limburg" },
      { word: "noord-brabant", meaning: "North Brabant" },
      { word: "polder", meaning: "polder" },
    ],
    name: "Mapping the Netherlands",
  },
  {
    words: [
      { word: "zingend", meaning: "singing" },
      { word: "spelend", meaning: "playing" },
      { word: "zittend", meaning: "sitting" },
      { word: "slapend", meaning: "sleeping" },
      { word: "huilend", meaning: "crying" },
      { word: "fietsend", meaning: "cycling" },
      { word: "vliegend", meaning: "flying" },
      { word: "groeiend", meaning: "growing" },
      { word: "verrassend", meaning: "surprising" },
      { word: "pratend", meaning: "talking" },
    ],
    name: "Present Participle",
  },
  {
    words: [
      { word: "drie", meaning: "three" },
      { word: "vier", meaning: "four" },
      { word: "één", meaning: "one" },
      { word: "vijf", meaning: "five" },
      { word: "meer", meaning: "more" },
      { word: "dan", meaning: "than" },
      { word: "minder", meaning: "fewer/less" },
      { word: "zes", meaning: "six" },
      { word: "zeven", meaning: "seven" },
      { word: "acht", meaning: "eight" },
    ],
    name: "Numbers",
  },
  {
    words: [
      { word: "oranje", meaning: "orange" },
      { word: "groen", meaning: "green" },
      { word: "grijs", meaning: "grey" },
      { word: "roze", meaning: "pink" },
      { word: "wit", meaning: "white" },
      { word: "bruin", meaning: "brown" },
      { word: "blauw", meaning: "blue" },
      { word: "geel", meaning: "yellow" },
      { word: "zwart", meaning: "black" },
      { word: "kleur", meaning: "color" },
    ],
    name: "Colors",
  },
  {
    words: [
      { word: "spreken", meaning: "speak" },
      { word: "lezen", meaning: "read" },
      { word: "drinken", meaning: "drink" },
      { word: "hebben", meaning: "have" },
      { word: "zijn", meaning: "be" },
      { word: "eten", meaning: "eat" },
      { word: "drink", meaning: "drink (imperative)" },
      { word: "spreek", meaning: "speak (imperative)" },
      { word: "lees", meaning: "read (imperative)" },
      { word: "ben", meaning: 'am (first person singular of "zijn")' },
    ],
    name: "Questions 1",
  },
  {
    words: [
      { word: "zijn", meaning: "be" },
      { word: "aan het", meaning: "in the process of" },
      { word: "lopen", meaning: "walk" },
      { word: "schrijven", meaning: "write" },
      { word: "lezen", meaning: "read" },
      { word: "zwemmen", meaning: "swim" },
      { word: "koken", meaning: "cook" },
      { word: "spelen", meaning: "play" },
      { word: "fietsen", meaning: "cycle" },
      { word: "werken", meaning: "work" },
    ],
    name: "Present Continuous",
  },
  {
    words: [
      { word: "zwembroek", meaning: "swimming trunks" },
      { word: "kinderschoen", meaning: "children's shoe" },
      { word: "varkensvlees", meaning: "pork" },
      { word: "hoofdkantoor", meaning: "headquarters" },
      { word: "winkelcentrum", meaning: "shopping center" },
      { word: "wc-papier", meaning: "toilet paper" },
      { word: "-avond", meaning: "-evening (suffix for evenings)" },
      { word: "-sap", meaning: "-juice (suffix for juices)" },
      { word: "-soep", meaning: "-soup (suffix for soups)" },
      { word: "-kleren", meaning: "-clothes (suffix for clothes)" },
    ],
    name: "Compound Nouns",
  },
  {
    words: [
      { word: "mening", meaning: "opinion" },
      { word: "standpunt", meaning: "point of view" },
      { word: "gelijk", meaning: "equal" },
      { word: "eerlijk", meaning: "fair" },
      { word: "eens", meaning: "agree" },
      { word: "aanraden", meaning: "recommend" },
      { word: "kwestie", meaning: "issue" },
      { word: "overtuigen", meaning: "convince" },
      { word: "onredelijk", meaning: "unreasonable" },
      { word: "accepteren", meaning: "accept" },
    ],
    name: "Opinions",
  },
  {
    words: [
      { word: "hallo", meaning: "hello" },
      { word: "bedankt", meaning: "thanks" },
      { word: "doei", meaning: "bye" },
      { word: "dag", meaning: "day" },
      { word: "tot ziens", meaning: "see you" },
      { word: "hoi", meaning: "hi" },
      { word: "goedemorgen", meaning: "good morning" },
      { word: "goedendag", meaning: "good day" },
      { word: "goedenavond", meaning: "good evening" },
      { word: "welterusten", meaning: "good night" },
    ],
    name: "Common Phrases",
  },
  {
    words: [
      { word: "droom", meaning: "dream" },
      { word: "idee", meaning: "idea" },
      { word: "kennis", meaning: "knowledge" },
      { word: "herinnering", meaning: "memory" },
      { word: "plan", meaning: "plan" },
      { word: "keuze", meaning: "choice" },
      { word: "verbeelding", meaning: "imagination" },
      { word: "geduld", meaning: "patience" },
      { word: "twijfel", meaning: "doubt" },
      { word: "verstand", meaning: "reason" },
    ],
    name: "Mind & Personality",
  },
  {
    words: [
      { word: "opstaan", meaning: "get up" },
      { word: "uitgaan", meaning: "go out" },
      { word: "neerzetten", meaning: "put down" },
      { word: "opschrijven", meaning: "write down" },
      { word: "invullen", meaning: "fill in" },
      { word: "weggaan", meaning: "leave" },
      { word: "meenemen", meaning: "take along" },
      { word: "aankomen", meaning: "arrive" },
      { word: "tegenkomen", meaning: "encounter" },
      { word: "afspreken", meaning: "arrange to meet" },
    ],
    name: "Seperatable Verbs",
  },
  {
    words: [
      { word: "sleutel", meaning: "key" },
      { word: "kamer", meaning: "room" },
      { word: "tuin", meaning: "garden" },
      { word: "raam", meaning: "window" },
      { word: "deur", meaning: "door" },
      { word: "slot", meaning: "lock" },
      { word: "woonkamer", meaning: "living room" },
      { word: "slaapkamer", meaning: "bedroom" },
      { word: "badkamer", meaning: "bathroom" },
      { word: "muur", meaning: "wall" },
    ],
    name: "Weather 1",
  },
  {
    words: [
      { word: "probleem", meaning: "problem" },
      { word: "geld", meaning: "money" },
      { word: "feest", meaning: "party" },
      { word: "er", meaning: "there" },
      { word: "stukje", meaning: "piece" },
      { word: "fles", meaning: "bottle" },
      { word: "wc", meaning: "toilet" },
      { word: "ding", meaning: "thing" },
      { word: "verbs", meaning: "verbs" },
      { word: "potlood", meaning: "pencil" },
    ],
    name: "Er",
  },
  {
    words: [
      { word: "worden", meaning: "become" },
      { word: "openen", meaning: "open" },
      { word: "presenteren", meaning: "present" },
      { word: "volgen", meaning: "follow" },
      { word: "steunen", meaning: "support" },
      { word: "bellen", meaning: "call" },
      { word: "zien", meaning: "see" },
      { word: "zijn", meaning: "be" },
      { word: "verkopen", meaning: "sell" },
      { word: "wassen", meaning: "wash" },
    ],
    name: "Passive voice",
  },
  {
    words: [
      { word: "ouder", meaning: "parent" },
      { word: "moeder", meaning: "mother" },
      { word: "vader", meaning: "father" },
      { word: "huis", meaning: "house" },
      { word: "familie", meaning: "family" },
      { word: "baby", meaning: "baby" },
      { word: "zus", meaning: "sister" },
      { word: "broer", meaning: "brother" },
      { word: "zoon", meaning: "son" },
      { word: "dochter", meaning: "daughter" },
    ],
    name: "My Family",
  },
  {
    words: [
      { word: "frisdrank", meaning: "soft drink" },
      { word: "boter", meaning: "butter" },
      { word: "salade", meaning: "salad" },
      { word: "chocolade", meaning: "chocolate" },
      { word: "pindakaas", meaning: "peanut butter" },
      { word: "olie", meaning: "oil" },
      { word: "koekje", meaning: "cookie" },
      { word: "slagroom", meaning: "whipped cream" },
      { word: "pannenkoek", meaning: "pancake" },
      { word: "snoep", meaning: "candy" },
    ],
    name: "More Food",
  },
  {
    words: [
      { word: "eenden", meaning: "ducks" },
      { word: "honden", meaning: "dogs" },
      { word: "twee", meaning: "two" },
      { word: "olifanten", meaning: "elephants" },
      { word: "dieren", meaning: "animals" },
      { word: "boeken", meaning: "books" },
      { word: "boterhammen", meaning: "sandwiches" },
      { word: "schildpadden", meaning: "turtles" },
      { word: "mensen", meaning: "people" },
      { word: "katten", meaning: "cats" },
    ],
    name: "Meervoud",
  },
  {
    words: [
      { word: "draag", meaning: "wear (I)" },
      { word: "draagt", meaning: "wear (you, he, she)" },
      { word: "schoen", meaning: "shoe" },
      { word: "broek", meaning: "pants" },
      { word: "jurk", meaning: "dress" },
      { word: "jas", meaning: "jacket" },
      { word: "kleren", meaning: "clothes" },
      { word: "sok", meaning: "sock" },
      { word: "dragen", meaning: "to wear" },
      { word: "trui", meaning: "sweater" },
    ],
    name: "Clothing",
  },
  {
    words: [
      { word: "nacht", meaning: "night" },
      { word: "middag", meaning: "afternoon" },
      { word: "tijd", meaning: "time" },
      { word: "dag", meaning: "day" },
      { word: "ochtend", meaning: "morning" },
      { word: "avond", meaning: "evening" },
      { word: "vandaag", meaning: "today" },
      { word: "morgen", meaning: "tomorrow" },
      { word: "vanavond", meaning: "tonight" },
      { word: "altijd", meaning: "always" },
    ],
    name: "Time",
  },
  {
    words: [
      { word: "wel", meaning: "well" },
      { word: "maar", meaning: "but" },
      { word: "wij", meaning: "we" },
      { word: "zij", meaning: "they" },
      { word: "jij", meaning: "you (informal)" },
      { word: "ook", meaning: "also" },
    ],
    name: "Marked & Unmarked Pronouns",
  },
  {
    words: [
      { word: "zo", meaning: "so" },
      { word: "even", meaning: "even" },
      { word: "net", meaning: "just" },
      { word: "precies", meaning: "exactly" },
      { word: "als", meaning: "as" },
      { word: "dan", meaning: "then" },
      { word: "groter", meaning: "bigger" },
      { word: "kleiner", meaning: "smaller" },
      { word: "langer", meaning: "longer" },
      { word: "sneller", meaning: "faster" },
    ],
    name: "Adjectives 3: Inflection",
  },
  {
    words: [
      { word: "viool", meaning: "violin" },
      { word: "instrument", meaning: "instrument" },
      { word: "noot", meaning: "note" },
      { word: "lied", meaning: "song" },
      { word: "akkoord", meaning: "chord" },
      { word: "zanger", meaning: "singer" },
      { word: "publiek", meaning: "audience" },
      { word: "theater", meaning: "theater" },
      { word: "dans", meaning: "dance" },
      { word: "toeschouwer", meaning: "spectator" },
    ],
    name: "Arts",
  },
  {
    words: [
      { word: "politiek", meaning: "politics" },
      { word: "nationaal", meaning: "national" },
      { word: "constitutionele monarchie", meaning: "constitutional monarchy" },
      { word: "regering", meaning: "government" },
      { word: "staat", meaning: "state" },
      { word: "vrij", meaning: "free" },
      { word: "kabinet", meaning: "cabinet" },
      { word: "premier", meaning: "prime minister" },
      { word: "advies", meaning: "advice" },
      { word: "voorzitter", meaning: "chairman/president" },
    ],
    name: "Politics",
  },
  {
    words: [
      { word: "bestaan", meaning: "to exist" },
      { word: "zingen", meaning: "to sing" },
      { word: "antwoorden", meaning: "to answer" },
      { word: "veroorzaken", meaning: "to cause" },
      { word: "delen", meaning: "to share" },
      { word: "verdwijnen", meaning: "to disappear" },
      { word: "bieden", meaning: "to offer" },
      { word: "steunen", meaning: "to support" },
      { word: "verwachten", meaning: "to expect" },
      { word: "eindigen", meaning: "to end" },
    ],
    name: "Verbs: Present 4",
  },
  {
    words: [
      { word: "brussel", meaning: "Brussels" },
      { word: "antwerpen", meaning: "Antwerp" },
      { word: "praline", meaning: "praline" },
      { word: "manneken pis", meaning: "Manneken Pis" },
      { word: "wafel", meaning: "waffle" },
      { word: "friet", meaning: "fries" },
      { word: "atomium", meaning: "Atomium" },
      { word: "gent", meaning: "Ghent" },
      { word: "cuberdon", meaning: "cuberdon" },
      { word: "kletskop", meaning: "brandy snap" },
    ],
    name: "Belgian Culture",
  },
  {
    words: [
      { word: "wees", meaning: "be" },
      { word: "kom", meaning: "come" },
      { word: "lezen", meaning: "read" },
      { word: "opruimen", meaning: "clean up" },
      { word: "blijven", meaning: "stay" },
      { word: "wacht", meaning: "wait" },
      { word: "laten", meaning: "let" },
      { word: "gaan", meaning: "go" },
      { word: "zingen", meaning: "sing" },
      { word: "dansen", meaning: "dance" },
    ],
    name: "Verbs: The Imperative",
  },
  {
    words: [
      { word: "groot", meaning: "big" },
      { word: "klein", meaning: "small" },
      { word: "grote", meaning: "big" },
      { word: "lang", meaning: "tall" },
      { word: "kleine", meaning: "small" },
      { word: "lange", meaning: "tall" },
      { word: "snel", meaning: "fast" },
      { word: "langzaam", meaning: "slow" },
      { word: "kort", meaning: "short" },
      { word: "snelle", meaning: "fast" },
    ],
    name: "Adjective Basics",
  },
  {
    words: [
      { word: "kunst", meaning: "art" },
      { word: "tekening", meaning: "drawing" },
      { word: "tekenen", meaning: "to draw" },
      { word: "lijn", meaning: "line" },
      { word: "liniaal", meaning: "ruler" },
      { word: "schets", meaning: "sketch" },
      { word: "schilder", meaning: "painter" },
      { word: "schilderij", meaning: "painting" },
      { word: "doek", meaning: "canvas" },
      { word: "verf", meaning: "paint" },
    ],
    name: "Arts 1",
  },
  {
    words: [
      { word: "tijdschrift", meaning: "magazine" },
      { word: "nieuws", meaning: "news" },
      { word: "internet", meaning: "internet" },
      { word: "tekst", meaning: "text" },
      { word: "media", meaning: "media" },
      { word: "artikel", meaning: "article" },
      { word: "pers", meaning: "press" },
      { word: "netwerk", meaning: "network" },
      { word: "uitzending", meaning: "broadcast" },
      { word: "website", meaning: "website" },
    ],
    name: "Communication 2",
  },
  {
    words: [
      { word: "ongerust", meaning: "worried" },
      { word: "geïrriteerd", meaning: "irritated" },
      { word: "opgewonden", meaning: "excited" },
      { word: "verward", meaning: "confused" },
      { word: "teleurgesteld", meaning: "disappointed" },
      { word: "geschrokken", meaning: "startled" },
      { word: "nieuwsgierig", meaning: "curious" },
      { word: "kwetsbaar", meaning: "vulnerable" },
      { word: "eenzaam", meaning: "lonely" },
      { word: "zenuwachtig", meaning: "nervous" },
    ],
    name: "Feelings",
  },
];
