const dutch = [
  {
    words: [
      "ongeveer",
      "echt",
      "vooral",
      "natuurlijk",
      "even",
      "zelfs",
      "toch",
      "binnenkort",
      "opnieuw",
      "gewoon",
    ],
    name: "Adverbs 2",
  },
  {
    words: [
      "schrijver",
      "baan",
      "schrijfster",
      "student",
      "studente",
      "werk",
      "carrière",
      "model",
      "kunstenaar",
      "kunstenares",
    ],
    name: "Occupations",
  },
  {
    words: [
      "zingen",
      "gaan",
      "zwemmen",
      "winnen",
      "verliezen",
      "fietsen",
      "rennen",
      "presenteren",
      "leven",
      "denken",
    ],
    name: "The gerund",
  },
  {
    words: [
      "vriezer",
      "koelkast",
      "magnetron",
      "fornuis",
      "oven",
      "hap",
      "roeren",
      "snijden",
      "lusten",
      "bakken",
    ],
    name: "Kitchen",
  },
  {
    words: [
      "volgens",
      "sinds",
      "dankzij",
      "behalve",
      "ondanks",
      "tegenover",
      "voorbij",
      "vanaf",
      "langs",
      "rondom",
    ],
    name: "Prepositions 2",
  },
  {
    words: [
      "succes",
      "verschil",
      "leven",
      "dood",
      "fout",
      "kans",
      "situatie",
      "gebeurtenis",
      "nadeel",
      "geheim",
    ],
    name: "Asbtract Objects 1",
  },
  {
    words: [
      "verhaal",
      "vertellen",
      "sturen",
      "brief",
      "informatie",
      "post",
      "discussie",
      "gesprek",
      "communicatie",
      "bericht",
    ],
    name: "Communication",
  },
  {
    words: [
      "prehistorie",
      "ridder",
      "middeleeuwen",
      "rijk",
      "aanval",
      "archeoloog",
      "burgeroorlog",
      "onafhankelijkheid",
      "tachtigjarige",
      "veldslag",
    ],
    name: "Events",
  },
  {
    words: [
      "leraar",
      "onderwijs",
      "school",
      "les",
      "klas",
      "leerling",
      "lesgeven",
      "voorbeeld",
      "huiswerk",
      "toets",
    ],
    name: "Education",
  },
  {
    words: [
      "fiets",
      "bus",
      "tram",
      "rijden",
      "motorfiets",
      "metro",
      "taxi",
      "weg",
      "verkeer",
      "vrachtwagen",
    ],
    name: "Traffic",
  },
  {
    words: [
      "studeren",
      "praten",
      "rennen",
      "wachten",
      "kiezen",
      "brengen",
      "begrijpen",
      "volgen",
      "vragen",
      "pakken",
    ],
    name: "Verbs: Present 3",
  },
  {
    words: [
      "huwelijk",
      "echtgenoot",
      "echtgenote",
      "gescheiden",
      "getrouwd",
      "bruiloft",
      "pa",
      "ma",
      "opa",
      "oma",
    ],
    name: "Vocab???",
  },
  {
    words: ["laten", "zien", "horen", "blijven", "moeten", "willen", "kunnen"],
    name: "Infinitives 2",
  },
  {
    words: [
      "handel",
      "economisch",
      "economie",
      "vraag",
      "aanbod",
      "beurs",
      "dollar",
      "valuta",
      "winst",
      "budget",
    ],
    name: "Economy",
  },
  {
    words: [
      "genoeg",
      "iedereen",
      "iemand",
      "iets",
      "alles",
      "men",
      "weinig",
      "alle",
      "veel",
      "sommige",
    ],
    name: "Indefinite Pronouns",
  },
  {
    words: [
      "me",
      "je",
      "zich",
      "wassen",
      "bewegen",
      "herinneren",
      "ons",
      "elkaar",
      "gedragen",
      "haasten",
    ],
    name: "Reflexives",
  },
  {
    words: [
      "zaken",
      "verzekering",
      "bedrijf",
      "fabriek",
      "klant",
      "eigenaar",
      "filiaal",
      "industrie",
      "belasting",
      "concurrentie",
    ],
    name: "Business",
  },
  {
    words: [
      "maat",
      "hoog",
      "grootte",
      "lengte",
      "laag",
      "vorm",
      "cirkel",
      "driehoek",
      "recht",
      "krom",
    ],
    name: "Shapes & Sizes",
  },
  {
    words: [
      "emotie",
      "boos",
      "blij",
      "bang",
      "huilen",
      "lachen",
      "bezorgd",
      "verdrietig",
      "gevoel",
      "trots",
    ],
    name: "Feelings 1",
  },
  {
    words: [
      "oorsprong",
      "actie",
      "reactie",
      "waarheid",
      "start",
      "werkelijkheid",
      "gastvrijheid",
      "ellende",
      "gelegenheid",
      "plezier",
    ],
    name: "Abstract Nouns 2",
  },
  {
    words: ["niet", "nee", "geen"],
    name: "Negatives 1",
  },
  {
    words: [
      "graag gedaan",
      "jammer",
      "inderdaad",
      "geen probleem",
      "eet smakelijk",
      "fijn",
      "welkom",
      "succes",
      "prima",
      "vaarwel",
    ],
    name: "Phrases 2",
  },
  {
    words: [
      "ploeg",
      "speler",
      "schoppen",
      "springen",
      "wedstrijd",
      "gooien",
      "doel",
      "punt",
      "voetbal",
      "scoren",
    ],
    name: "Sports",
  },
  {
    words: [
      "douche",
      "toilet",
      "kraan",
      "gootsteen",
      "handdoek",
      "bad",
      "shampoo",
      "droog",
      "nat",
      "zeep",
    ],
    name: "Bathroom",
  },
  {
    words: [
      "gaan",
      "zullen",
      "veranderen",
      "kiezen",
      "breken",
      "regenen",
      "verliezen",
      "overmorgen",
      "winnen",
      "ooit",
    ],
    name: "Future verbs",
  },
  {
    words: [
      "bloem",
      "tulp",
      "gras",
      "natuur",
      "plant",
      "groeien",
      "land",
      "leven",
      "gewas",
      "zand",
    ],
    name: "Nature",
  },
  {
    words: [
      "maandag",
      "zondag",
      "zaterdag",
      "donderdag",
      "vrijdag",
      "woensdag",
      "dinsdag",
      "week",
      "jaar",
      "weekend",
    ],
    name: "Time",
  },
  {
    words: [
      "kijken",
      "oog",
      "lijken",
      "foto",
      "bekijken",
      "uitzicht",
      "luisteren",
      "muziek",
      "geluid",
      "oor",
    ],
    name: "Senses",
  },
  {
    words: [
      "normaal",
      "mogelijk",
      "perfect",
      "tenminste",
      "nauwelijks",
      "tegelijk",
      "momenteel",
      "voldoende",
      "echter",
      "zeer",
    ],
    name: "Adverbs 2",
  },
  {
    words: [
      "erin",
      "erop",
      "ermee",
      "ernaar",
      "ernaast",
      "er-",
      "eruit",
      "ertussen",
      "ervandaan",
      "erheen",
    ],
    name: "Pronominal Adverbs",
  },
  {
    words: [
      "kan",
      "kunt",
      "willen",
      "wil",
      "kunnen",
      "mag",
      "moeten",
      "mogen",
      "blijven",
      "komen",
    ],
    name: "Modal verbs",
  },
  {
    words: [
      "god",
      "godin",
      "bidden",
      "religie",
      "geloof",
      "gelovig",
      "gebed",
      "geest",
      "ziel",
      "priesteres",
    ],
    name: "Spiritual & Religion",
  },
  {
    words: ["u", "uw", "alstublieft", "meneer", "mevrouw", "dank u wel"],
    name: "Formal",
  },
  {
    words: [
      "eenentwintig",
      "tweeëntwintig",
      "drieëntwintig",
      "vierentwintig",
      "vijfentwintig",
      "zesentwintig",
      "zevenentwintig",
      "achtentwintig",
      "negenentwintig",
      "dertig",
    ],
    name: "Numbers 2",
  },
  {
    words: [
      "wie",
      "waar",
      "wat",
      "waarom",
      "hoe",
      "wiens",
      "welk",
      "welke",
      "hoeveel",
      "wanneer",
    ],
    name: "Questions",
  },
  {
    words: [
      "aantekening",
      "cursus",
      "aanmelding",
      "universiteit",
      "lezing",
      "professor",
      "verslag",
      "programma",
      "college",
      "document",
    ],
    name: "University",
  },
  {
    words: ["nu", "soms", "daar", "hier", "misschien"],
    name: "Inversion",
  },
  {
    words: [
      "verkiezing",
      "kiezer",
      "lid",
      "stemmen",
      "partij",
      "leden",
      "eisen",
      "kandidaat",
      "campagne",
      "regel",
    ],
    name: "Politics",
  },
  {
    words: [
      "om",
      "te",
      "zonder",
      "door",
      "pronouns",
      "vragen om",
      "beginnen",
      "proberen",
      "vergeten",
      "leren",
    ],
    name: "Te + infinitive verbs",
  },
  {
    words: [
      "schoonheid",
      "vrijheid",
      "eerlijkheid",
      "verantwoordelijkheid",
      "mogelijkheid",
      "moeilijkheid",
      "beweging",
      "verandering",
      "bestelling",
      "opening",
    ],
    name: "Suffixes",
  },
  {
    words: [
      "strand",
      "stad",
      "gebouw",
      "hotel",
      "steden",
      "restaurant",
      "adres",
      "route",
      "straat",
      "dorp",
    ],
    name: "Places",
  },
  {
    words: [
      "omhoog",
      "omlaag",
      "vooruit",
      "achteruit",
      "links",
      "rechts",
      "rechtsaf",
      "rechtdoor",
      "afslaan",
      "linksaf",
    ],
    name: "Directions",
  },
  {
    words: [
      "eten",
      "boterham",
      "drinken",
      "rijst",
      "jullie",
      "we",
      "vrouwen",
      "lezen",
      "de",
      "mannen",
    ],
    name: "Basics 2",
  },
  {
    words: [
      "hebben",
      "gisteren",
      "gespeeld",
      "geregend",
      "gewerkt",
      "geluisterd",
      "gekookt",
      "gevraagd",
      "gewacht",
      "gezet",
    ],
    name: "Present Perfect: Regular/Weak Verbs",
  },
  {
    words: [
      "betaald",
      "gebeurd",
      "gebleven",
      "geopend",
      "vertrokken",
      "eergisteren",
      "genomen",
      "gesproken",
      "verkocht",
      "bezocht",
    ],
    name: "Verbs: Present Perfect",
  },
  {
    words: [
      "vis",
      "wijn",
      "thee",
      "koffie",
      "ei",
      "kip",
      "suiker",
      "middageten",
      "ontbijt",
      "kaas",
    ],
    name: "Eten",
  },
  {
    words: [
      "patiënt",
      "gezond",
      "ongeluk",
      "zorg",
      "medicijn",
      "ziek",
      "behandeling",
      "pijn",
      "gezondheid",
      "ziekte",
    ],
    name: "Medical",
  },
  {
    words: [
      "bouwen",
      "dak",
      "lift",
      "verdieping",
      "trap",
      "plafond",
      "uitgang",
      "ingang",
      "gang",
      "balkon",
    ],
    name: "Buildings",
  },
  {
    words: [
      "hand",
      "lichaam",
      "hoofd",
      "bloed",
      "zorgen",
      "haar",
      "hart",
      "huid",
      "nek",
      "gezicht",
    ],
    name: "Medical",
  },
  {
    words: [
      "machine",
      "batterij",
      "televisie",
      "gereedschap",
      "radio",
      "apparaat",
      "stopcontact",
      "rekenmachine",
      "stekker",
      "knop",
    ],
    name: "Technology",
  },
  {
    words: [
      "beroemd",
      "algemeen",
      "fantastisch",
      "onmogelijk",
      "mogelijk",
      "belgisch",
      "serieus",
      "uitstekend",
      "beschikbaar",
      "bloot",
    ],
    name: "Adjectives 3",
  },
  {
    words: [
      "man",
      "vrouw",
      "ik",
      "ben",
      "jongen",
      "een",
      "en",
      "is",
      "ze",
      "of",
    ],
    name: "Basics 1",
  },
  {
    words: [
      "zon",
      "weer",
      "regen",
      "wind",
      "storm",
      "schijnen",
      "wolk",
      "mist",
      "regenboog",
      "sneeuw",
    ],
    name: "Weather",
  },
  {
    words: [
      "kat",
      "dier",
      "hond",
      "vogel",
      "muis",
      "mens",
      "olifant",
      "eend",
      "schildpad",
      "paard",
    ],
    name: "Dieren",
  },
  {
    words: ["nu", "soms", "daar", "hier", "misschien"],
    name: "No Inversion",
  },
  {
    words: [
      "net",
      "gegeten",
      "gezien",
      "gelezen",
      "geschreven",
      "gekomen",
      "geslapen",
      "gestaan",
      "nadat",
      "geweest",
    ],
    name: "Present Perfect: Strong Verbs",
  },
  {
    words: [
      "was",
      "waren",
      "had",
      "hadden",
      "deed",
      "deden",
      "willen",
      "spelen",
      "toen",
      "horen",
    ],
    name: "Simple Past 1",
  },
  {
    words: [
      "oostelijk",
      "westelijk",
      "halfrond",
      "noordelijk",
      "zuidelijk",
      "ontdekken",
      "europa",
      "azië",
      "afrika",
      "noord-amerika",
    ],
    name: "Mapping the world: Geography",
  },
  {
    words: [
      "bioscoop",
      "film",
      "festival",
      "toneel",
      "concert",
      "band",
      "kasteel",
      "toren",
      "museum",
      "pretpark",
    ],
    name: "Leisure",
  },
  {
    words: [
      "gebruikt",
      "toegevoegd",
      "gekookt",
      "geleend",
      "beschermd",
      "vertaald",
      "on-",
      "gelezen",
      "gestolen",
      "deelwoorden",
    ],
    name: "Past Participle",
  },
  {
    words: [
      "staan",
      "denken",
      "zeggen",
      "werken",
      "heten",
      "leren",
      "helpen",
      "nodig hebben",
      "gebruiken",
      "kopen",
    ],
    name: "Verbs: Present 2",
  },
  {
    words: [
      "pakjesavond",
      "sinterklaas",
      "oudejaarsavond",
      "nieuwjaar",
      "vieren",
      "cadeau",
      "pasen",
      "kerstmis",
      "koningsdag",
      "traditie",
    ],
    name: "Holidays",
  },
  {
    words: [
      "dat",
      "wie",
      "waar",
      "wat",
      "die",
      "degene",
      "van wie",
      "diegene",
      "wiens",
      "datgene",
    ],
    name: "Pronouns relative",
  },
  {
    words: [
      "zitten",
      "doos",
      "auto",
      "mand",
      "in",
      "liggen",
      "amsterdam",
      "deken",
      "bal",
      "park",
    ],
    name: "Staan/Liggen/Zitten",
  },
  {
    words: ["maar", "want", "of", "dus", "en"],
    name: "Conjunctions 1: Coordinating",
  },
  {
    words: [
      "wetenschap",
      "onderzoek",
      "laboratorium",
      "theorie",
      "experiment",
      "uitvoeren",
      "methode",
      "wetenschappelijk",
      "formule",
      "definitie",
    ],
    name: "Science",
  },
  {
    words: [
      "eenheid",
      "snelheid",
      "afstand",
      "liter",
      "massa",
      "kilogram",
      "bedragen",
      "diepte",
      "meten",
      "hoogte",
    ],
    name: "Science! 2",
  },
  {
    words: [
      "zouden",
      "zou",
      "moeten",
      "veranderen",
      "doen",
      "kiezen",
      "willen",
      "vinden",
      "eten",
      "was",
    ],
    name: "The Conditional",
  },
  {
    words: [
      "politie",
      "taak",
      "beschermen",
      "hulp",
      "bellen",
      "politieagent",
      "arrestatie",
      "misdaad",
      "plegen",
      "stelen",
    ],
    name: "Services",
  },
  {
    words: [
      "euro",
      "cent",
      "kosten",
      "verkopen",
      "winkel",
      "te koop",
      "gratis",
      "supermarkt",
      "boodschappen",
      "slagerij",
    ],
    name: "Shopping",
  },
  {
    words: [
      "had",
      "hadden",
      "gehoord",
      "verwacht",
      "besloten",
      "gezien",
      "geprobeerd",
      "geroepen",
      "verloren",
      "gebeld",
    ],
    name: "The past perfect/pluperfect",
  },
  {
    words: [
      "dit",
      "die",
      "dat",
      "deze",
      "beide",
      "zo'n",
      "zulke",
      "zulk",
      "al",
      "zoiets",
    ],
    name: "Determiners",
  },
  {
    words: [
      "maan",
      "aarde",
      "draaien",
      "rond",
      "ruimte",
      "ster",
      "zonnestelsel",
      "planeet",
      "sterrenkunde",
      "universum",
    ],
    name: "Space",
  },
  {
    words: [
      "briefje",
      "doosje",
      "huisje",
      "mandje",
      "lampje",
      "kastje",
      "mannetje",
      "blaadje",
      "vrouwtje",
      "raampje",
    ],
    name: "Diminutives",
  },
  {
    words: [
      "reizen",
      "reist",
      "reis",
      "amerika",
      "frankrijk",
      "duitsland",
      "buitenland",
      "vlucht",
      "boeken",
      "koffer",
    ],
    name: "Travel",
  },
  {
    words: [
      "romantisch",
      "passie",
      "kussen",
      "relatie",
      "knuffelen",
      "liefde",
      "verkering",
      "hetero",
      "homo",
      "aantrekkelijk",
    ],
    name: "Romance & Relationships",
  },
  {
    words: [
      "goed",
      "rustig",
      "al",
      "snel",
      "langzaam",
      "dan",
      "ook",
      "nog",
      "heel",
      "steeds",
    ],
    name: "Adverbs",
  },
  {
    words: [
      "loop",
      "loopt",
      "lopen",
      "schrijf",
      "schrijft",
      "schrijven",
      "zwemmen",
      "zwemt",
      "zwem",
      "koken",
    ],
    name: "Verbs: Present",
  },
  {
    words: [
      "vla",
      "hagelslag",
      "appelflap",
      "poffertje",
      "stroopwafel",
      "drop",
      "vlaai",
      "kroket",
      "café",
      "bakje troost",
    ],
    name: "Dutch Food and Snacks",
  },
  {
    words: [
      "duits",
      "frans",
      "portugees",
      "spaans",
      "russisch",
      "chinees",
      "taal",
      "hebreeuws",
      "arabisch",
      "fries",
    ],
    name: "Language",
  },
  {
    words: [
      "meer",
      "land",
      "eiland",
      "bos",
      "zee",
      "rivier",
      "berg",
      "landschap",
      "woestijn",
      "kust",
    ],
    name: "Geography",
  },
  {
    words: [
      "verkouden",
      "doof",
      "niezen",
      "hoesten",
      "blind",
      "overgeven",
      "dodelijk",
      "giftig",
      "duizelig",
      "hoofdpijn",
    ],
    name: "Medical",
  },
  {
    words: ["haar", "hem", "mij", "me", "het", "jou", "ons", "je", "ze", "hun"],
    name: "Objective pronouns",
  },
  {
    words: [
      "metaal",
      "zilver",
      "ijzer",
      "hout",
      "goud",
      "plastic",
      "katoen",
      "wol",
      "zijde",
      "leer",
    ],
    name: "Materials",
  },
  {
    words: [
      "wanneer",
      "als",
      "hoewel",
      "tenzij",
      "dat",
      "zodat",
      "terwijl",
      "totdat",
      "of",
      "omdat",
    ],
    name: "Conjunctions",
  },
  {
    words: [
      "eng",
      "echt",
      "saai",
      "rijk",
      "arm",
      "verkeerd",
      "voorzichtig",
      "gevaarlijk",
      "favoriet",
      "raar",
    ],
    name: "Adjectives 2",
  },
  {
    words: [
      "in",
      "naar",
      "op",
      "nederland",
      "wonen",
      "belgië",
      "voor",
      "naast",
      "uit",
      "met",
    ],
    name: "Prepositions",
  },
  {
    words: [
      "nooit",
      "niemand",
      "niets",
      "nergens",
      "noch",
      "niks",
      "meer",
      "nog niet",
      "helemaal niet",
      "geen enkel",
    ],
    name: "Negatives 2",
  },
  {
    words: [
      "at",
      "aten",
      "sprak",
      "drinken",
      "spraken",
      "lopen",
      "liggen",
      "zag",
      "zagen",
      "zeiden",
    ],
    name: "Verbs Past: 1",
  },
  {
    words: [
      "kapsel",
      "baard",
      "kaal",
      "snor",
      "blond",
      "uiterlijk",
      "veter",
      "rits",
      "knap",
      "knoop",
    ],
    name: "Appearance 2",
  },
  {
    words: [
      "samenleving",
      "cultuur",
      "stichting",
      "gemeenschap",
      "armoede",
      "welvaart",
      "gelijkheid",
      "samenwerking",
      "chaos",
      "vooruitgang",
    ],
    name: "Society",
  },
  {
    words: [
      "zijn",
      "mijn",
      "onze",
      "hun",
      "jouw",
      "haar",
      "van",
      "naam",
      "jou",
      "ons",
    ],
    name: "Possessives",
  },
  {
    words: [
      "burger",
      "bevolking",
      "buur",
      "persoon",
      "jeugd",
      "groep",
      "dame",
      "koppel",
      "volwassene",
      "heer",
    ],
    name: "People",
  },
  {
    words: [
      "groningen",
      "provincie",
      "utrecht",
      "gracht",
      "rotterdam",
      "friesland",
      "dijk",
      "limburg",
      "noord-brabant",
      "polder",
    ],
    name: "Mapping the Netherlands",
  },
  {
    words: [
      "zingend",
      "spelend",
      "zittend",
      "slapend",
      "huilend",
      "fietsend",
      "vliegend",
      "groeiend",
      "verrassend",
      "pratend",
    ],
    name: "Present Participle",
  },
  {
    words: [
      "drie",
      "vier",
      "één",
      "vijf",
      "meer",
      "dan",
      "minder",
      "zes",
      "zeven",
      "acht",
    ],
    name: "Numbers",
  },
  {
    words: [
      "oranje",
      "groen",
      "grijs",
      "roze",
      "wit",
      "bruin",
      "blauw",
      "geel",
      "zwart",
      "kleur",
    ],
    name: "Colors",
  },
  {
    words: [
      "spreken",
      "lezen",
      "drinken",
      "hebben",
      "zijn",
      "eten",
      "drink",
      "spreek",
      "lees",
      "ben",
    ],
    name: "Questions 1",
  },
  {
    words: [
      "zijn",
      "aan het",
      "lopen",
      "schrijven",
      "lezen",
      "zwemmen",
      "koken",
      "spelen",
      "fietsen",
      "werken",
    ],
    name: "Present Continuous",
  },
  {
    words: [
      "zwembroek",
      "kinderschoen",
      "varkensvlees",
      "hoofdkantoor",
      "winkelcentrum",
      "wc-papier",
      "-avond",
      "-sap",
      "-soep",
      "-kleren",
    ],
    name: "Compound Nouns",
  },
  {
    words: [
      "mening",
      "standpunt",
      "gelijk",
      "eerlijk",
      "eens",
      "aanraden",
      "kwestie",
      "overtuigen",
      "onredelijk",
      "accepteren",
    ],
    name: "Opinions",
  },
  {
    words: [
      "hallo",
      "bedankt",
      "doei",
      "dag",
      "tot ziens",
      "hoi",
      "goedemorgen",
      "goedendag",
      "goedenavond",
      "welterusten",
    ],
    name: "Common Phrases",
  },
  {
    words: [
      "droom",
      "idee",
      "kennis",
      "herinnering",
      "plan",
      "keuze",
      "verbeelding",
      "geduld",
      "twijfel",
      "verstand",
    ],
    name: "Mind & Personality",
  },
  {
    words: [
      "opstaan",
      "uitgaan",
      "neerzetten",
      "opschrijven",
      "invullen",
      "weggaan",
      "meenemen",
      "aankomen",
      "tegenkomen",
      "afspreken",
    ],
    name: "Seperatable Verbs",
  },
  {
    words: [
      "sleutel",
      "kamer",
      "tuin",
      "raam",
      "deur",
      "slot",
      "woonkamer",
      "slaapkamer",
      "badkamer",
      "muur",
    ],
    name: "Weather 1",
  },
  {
    words: [
      "probleem",
      "geld",
      "feest",
      "er",
      "stukje",
      "fles",
      "wc",
      "ding",
      "verbs",
      "potlood",
    ],
    name: "Er",
  },
  {
    words: [
      "worden",
      "openen",
      "presenteren",
      "volgen",
      "steunen",
      "bellen",
      "zien",
      "zijn",
      "verkopen",
      "wassen",
    ],
    name: "Passive voice",
  },
  {
    words: [
      "ouder",
      "moeder",
      "vader",
      "huis",
      "familie",
      "baby",
      "zus",
      "broer",
      "zoon",
      "dochter",
    ],
    name: "My Family",
  },
  {
    words: [
      "frisdrank",
      "boter",
      "salade",
      "chocolade",
      "pindakaas",
      "olie",
      "koekje",
      "slagroom",
      "pannenkoek",
      "snoep",
    ],
    name: "More Food",
  },
  {
    words: [
      "eenden",
      "honden",
      "twee",
      "olifanten",
      "dieren",
      "boeken",
      "boterhammen",
      "schildpadden",
      "mensen",
      "katten",
    ],
    name: "Meervoud",
  },
  {
    words: [
      "draag",
      "draagt",
      "schoen",
      "broek",
      "jurk",
      "jas",
      "kleren",
      "sok",
      "dragen",
      "trui",
    ],
    name: "Clothing",
  },
  {
    words: [
      "nacht",
      "middag",
      "tijd",
      "dag",
      "ochtend",
      "avond",
      "vandaag",
      "morgen",
      "vanavond",
      "altijd",
    ],
    name: "Time",
  },
  {
    words: ["wel", "maar", "wij", "zij", "jij", "ook"],
    name: "Marked & Unmarked Pronouns",
  },
  {
    words: [
      "zo",
      "even",
      "net",
      "precies",
      "als",
      "dan",
      "groter",
      "kleiner",
      "langer",
      "sneller",
    ],
    name: "Adjectives 3: Inflection",
  },
  {
    words: [
      "viool",
      "instrument",
      "noot",
      "lied",
      "akkoord",
      "zanger",
      "publiek",
      "theater",
      "dans",
      "toeschouwer",
    ],
    name: "Arts",
  },
  {
    words: [
      "politiek",
      "nationaal",
      "constitutionele monarchie",
      "regering",
      "staat",
      "vrij",
      "kabinet",
      "premier",
      "advies",
      "voorzitter",
    ],
    name: "Politics",
  },
  {
    words: [
      "bestaan",
      "zingen",
      "antwoorden",
      "veroorzaken",
      "delen",
      "verdwijnen",
      "bieden",
      "steunen",
      "verwachten",
      "eindigen",
    ],
    name: "Verbs: Present 4",
  },
  {
    words: [
      "brussel",
      "antwerpen",
      "praline",
      "manneken pis",
      "wafel",
      "friet",
      "atomium",
      "gent",
      "cuberdon",
      "kletskop",
    ],
    name: "Belgian Culture",
  },
  {
    words: [
      "wees",
      "kom",
      "lezen",
      "opruimen",
      "blijven",
      "wacht",
      "laten",
      "gaan",
      "zingen",
      "dansen",
    ],
    name: "Verbs: The Imperative",
  },
  {
    words: [
      "groot",
      "klein",
      "grote",
      "lang",
      "kleine",
      "lange",
      "snel",
      "langzaam",
      "kort",
      "snelle",
    ],
    name: "Adjective Basics",
  },
  {
    words: [
      "kunst",
      "tekening",
      "tekenen",
      "lijn",
      "liniaal",
      "schets",
      "schilder",
      "schilderij",
      "doek",
      "verf",
    ],
    name: "Arts 1",
  },
  {
    words: [
      "tijdschrift",
      "nieuws",
      "internet",
      "tekst",
      "media",
      "artikel",
      "pers",
      "netwerk",
      "uitzending",
      "website",
    ],
    name: "Communication 2",
  },
  {
    words: [
      "ongerust",
      "geïrriteerd",
      "opgewonden",
      "verward",
      "teleurgesteld",
      "geschrokken",
      "nieuwsgierig",
      "kwetsbaar",
      "eenzaam",
      "zenuwachtig",
    ],
    name: "Feelings",
  },
];
