export const prevSelected = [
  "fles : bottle",
  "bevat : contains",
  "dorstige : thirsty",
  "zwembad : pool",
  "speelplaats : playground",
  "rij : line",
  "schommel : swings",
  "glijbaan : slide",
  "vochtig : humid",
  "graden : degrees",
  "bevriest : freezes",
  "serveerster : waitress",
  "blad : tray",
  "vasthouden: to hold",
  "morste : spilled",
  "kleding : clothes",
  "opbergen : putting away",
  "vegen : sweeping",
  "houten : wooden",
  "spiegel : mirror",
  "muur : wall",
  "kocht : bought",
  "boekenplank : bookshelf",
  "bitterzoete : bittersweet",
  "nasmaak : aftertaste",
  "voorkomende : common",
  "frisdranken : soft drinks",
  "smaakstof : flavored",
  "rustgevend : comforting",
  "van houden : to love",
  "spannende : suspense",
  "lachen : laughing",
  "kruidenierswaren : grocery",
  "stoffen tas : cloth bags",
  "winkelwagen : shopping cart",
  "leeg : empty",
  "leuning : handrail",
  "herinneren : remember",
  "doos : box",
  "bovenste : top",
  "plank : shelf",
  "zetten : put",
  "achtergrond : background",
  "ken : know",
  "natuurkunde : physics",
  "plek : place",
  "scheikunde : chemistry",
  "koffer : suitcase",
  "waardevolle : valuable",
  "dingen : things",
  "verlaten : leave",
  "achterlaten : leave",
  "achter : behind",
  "landkaart : map",
  "bestemming : destination",
  "kom : bowl",
  "gootsteen : sink",
  "snijplank : cutting board",
  "Snijden : cut",
  "stop : put",
  "map : folder",
  "alleen : only",
  "Ondernemers : Entrepreneurs",
  "veranderd : change",
  "soldaten : soldiers",
  "verplaatsen : move",
  "zich : themselves",
  "kunstenaars : artists",
  "voordat : before",
  "eerst : first",
  "soorten : kinds",
  "ontwerpers : designers",
  "kledingontwerper : fashion designer",
  "ratelslang : rattlesnake",
  "opgerold : coiled",
  "klaar : ready",
  "betekenen : to mean",
  "toe slaan : strike",
  "Mieren : Ants",
  "poten : legs",
  "bij : bee",
  "bestuift : Pollinates",
  "bord : plate",
  "vies : dirty",
  "aangeven : pass",
  "mes : knife",
  "gemaakt : made",
  "lepels : spoons",
  "bestek : eating utensils",
  "handdoek : towel",
  " washand : washcloth",
  "baard : beard",
  "scheren : shave",
  "wegwerp : disposable",
  "scheermes : shaving razor",
  "woon : live",
  "achtste : eighth",
  "verdieping : floor",
  "Tijdens : During",
  "tiende : tenth",
  "poging : attempt",
  "eindelijk : finally",
  "negende : ninth",
  "bevat : contains",
  "zwaar : heavy",
  "Kruiderijen : seasonings",
  "specerijen : Spices",
  "gangpad : aisle",
  "wat : some",
  "om : to",
  "geschiedenis : history",
  "ijs : Ice",
  "gevormd : formed",
  "waar dan ook : anywhere",
  "bouwvakker : construction worker",
  "meet : measure",
  "hout : wood",
  "vervelende : nasty",
  "mug : mosquito",
  "kakkerlak : cockroach",
  "vleugels : wings",
  " Kraaien : Crows",
  "behoren : belong",
  "slimste : smartest",
  "vloeibare : liquid",
  "zeep : soap",
  "voorkom : avoid",
  "Spoelen : Rinse",
  "gedurende : during",
  "wedstrijd : contest",
  "enge : scary",
  "vierde : fourth",
  "vijfde : fifth",
  "zesde : sixth",
  "zevende : seventh",
  "Gisteren : Yesterday",
  "ging : went",
  "uitverkoop : sale",
  "afdeling : department",
  "tekening : picture",
  "tekenen : draw",
  "liefde : love",
  "vak : subject",
  "wiskunde : math",
  "wetenschap : science",
  "graag : please",
  "Ontmoet : Meet",
  "gids : guide",
  "reisgids : guidebook",
  "handige : helpful",
  "duiven : pigeons",
  "voeren : feed",
  "Kikkers : Frogs",
  "vangen : catch",
  "pan : pot",
  "fornuis : stove",
  "zou : would",
  "steeds : always",
  "Meer : More",
  "minder : less",
  "telefooncel : phone booth",
  "tandarts : dentist",
  "eigenlijk : really",
  "lening : loan",
  "boer : farmer",
  "tarwe : wheat",
  "verzamel : gather",
  "zonder : without",
  "tandpasta : toothpaste",
  "tandenborstel : toothbrush",
  "ooit : ever",
  "volgende : next",
  "Sla : Turn",
  "rechtdoor : straight",
  "kruising : intersection",
  "dop : shell",
  "vieren : celebrate",
  "vandaag : today",
  "wat : kind of",
  "vermoeiend : tiring",
  "klachten : complaints",
  "raam : window",
  "gang : hallway",
  "einde : end",
  "eettafel : dinner table",
  "eetkamer : dining room",
  "ruimte : space",
  "woonkamer : living room",
  "stropdassen : ties",
  "werknemers : employees",
  "Vanwege : due to",
  "vertrekken : leave",
  "vluchten : flights",
  "vanaf : from",
  "vliegveld : airport",
  "belangrijk : important",
  "keer : time",
  "tanden : teeth",
  "poetsen : brush",
  "vergadering : meeting",
  "zin : feel like",
  "uitdoen : turn off",
  "uitschakelen : turn off",
  "schakelen : switch",
  "Ambtenaren : Civil servants",
  "formulieren : forms",
  "geboortedatum : date of birth",
  "dichtdoen : close",
  "stel : ask",
  "antwoord : answer",
  "gewoon : just",
  "geweldig : great",
  "stuk : piece",
  "kunst : art",
  "vaak : often",
  "tussendoortje : snack",
  "pendelen : commute",
  "beha : brassiere",
  "tenminste : at least",
  "gelijk : immediately",
  "terugbrengen : return",
  "terug : back",
  "wijzen : to point",
  "stoel : chair",
  "bureau : desk",
  "vast : attached",
  "klaslokaal : classroom",
  "tegenover : across from",
  "gelijk : equal",
  "paginas : pages",
  "gebouw : building",
  "veters : laces",
  "zolen : soles",
  "Behalve : except",
  "stropdas : necktie",
  "fatsoenlijk : properly",
  "knopen : knot",
  "slons : slob",
  "uitleggen : explain",
  "aantal : amount",
  "trouwerijen : weddings",
  "omdat : because",
  "geluk : luck",
  "verschillende : different",
  "gebruiken : traditions",
  "toepassen : use",
  "begrafenissen : funerals",
  "jubileum : anniversary",
  "aangeven : mark",
  "uitnodigen : invite",
  "afstuderen : graduation",
  "schoonmaken : to clean",
  "Helaas : Unfortunately",
  "Trek uit : Take off",
  "halen : fetch",
  "bankpas : Debit card",
  "munt : coin",
  "erg : very",
  "riem : belt",
  "afval : waste",
  "verminderen : reduce",
  "vorig : last",
];
